/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.shishmakov;

public class App {
    public void start(String param) {
        switch (param) {
            case "numberOfIslands": {
                new NumberOfIslands().run();
                break;
            }
            default: {
                throw new IllegalArgumentException("Unavailable param: " + param);
            }
        }
    }

    public static void main(String[] args) {
        if (args.length == 0) {
            throw new IllegalStateException("No params in args array");
        }
        new App().start(args[0]);
    }
}
