/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.shishmakov;

import java.util.Objects;

public class App {
    public void start(String param) {
        switch (param) {
            case "numberOfIslands": {
                new NumberOfIslands().run();
                break;
            }
            default: {
                throw new IllegalArgumentException("unavailable param: " + param);
            }
        }
    }

    public static void main(String[] args) {
        Objects.requireNonNull(args[0], "param is null");
        new App().start(args[0]);
    }
}
